# Routing Manager Configuration

# MongoDB Configuration
mongodb:
  host: ${MONGODB_HOST}
  port: ${MONGODB_PORT}
  username: ${MONGODB_USERNAME}
  password: ${MONGODB_PASSWORD}
  timeout: "10s"

# Monitoring Manager Configuration
monitoring_manager:
  host: ${MONITORING_MANAGER_HOST}
  port: ${MONITORING_MANAGER_PORT}


# Processor (RoutingManager) Configuration
processor:
  task_topic: "tasks"
  result_topic: "results" 