services:
  # Routing Manager
  routing-manager:
    image: routing-manager:latest
    container_name: routing-manager
    hostname: routing-manager
    environment:
      - ROUTING_MANAGER_HTTP_SERVER_PORT=${ROUTING_MANAGER_HTTP_SERVER_PORT}
      - MQTT_BROKER_HOST=${MQTT_BROKER_URL}
      - MQTT_BROKER_PORT=${MQTT_BROKER_PORT}
      - MQTT_CLIENT_ID=${ROUTING_MANAGER_MQTT_CLIENT_ID}
      - MQTT_USERNAME=${ROUTING_MANAGER_MQTT_USERNAME}
      - MQTT_PASSWORD=${ROUTING_MANAGER_MQTT_PASSWORD}
      - MQTT_QOS=${ROUTING_MANAGER_MQTT_QOS}
      - MQTT_CLEAN_SESSION=${ROUTING_MANAGER_MQTT_CLEAN_SESSION}
      - MQTT_CONNECT_TIMEOUT=${ROUTING_MANAGER_MQTT_CONNECT_TIMEOUT}
      - MONITORING_MANAGER_HOST=${MONITORING_MANAGER_HOST}
      - MONITORING_MANAGER_PORT=${MONITORING_MANAGER_HTTP_PORT}
      - SERVICE_MANAGER_HOST=${SERVICE_MANAGER_URL}
      - SERVICE_MANAGER_PORT=${SERVICE_MANAGER_PORT}
      - MONGODB_HOST=${MONGODB_NET_URL}
      - MONGODB_PORT=${MONGODB_NET_PORT}
      - LOG_FORMAT=console
      - LOG_LEVEL=info
    volumes:
      - ${ROUTING_MANAGER_CONFIG_PATH}:/app/config.yaml
    ports:
      - ${ROUTING_MANAGER_HTTP_SERVER_PORT}:${ROUTING_MANAGER_HTTP_SERVER_PORT}
    restart: unless-stopped
