receivers:
  http:
    endpoint:
      ip: 127.0.0.1
      port: &port 1880

exporters:
  debug:
    verbosity: detailed

  mqtt:
    interval: 1s
    client_id: routing_manager
    # TODO: set maybe wildcard topic name
    topic: routing/update
    broker:
      host: 127.0.0.1
      port: 1883

processors:

service:
  telemetry:
    metrics:
      level: none
  pipelines:
    metrics:
      receivers: [http]
      processors: []
      exporters: [mqtt, debug]
